---
galaxy_info:
  author: Steve Fulmer
  description: Normalize infra.windows_ops STIG results to Common Findings Format (CFF)
  license: Apache-2.0
  min_ansible_version: "2.16"
  platforms:
    - name: Windows
      versions:
        - "2019"
        - "2022"
        - "2025"
  galaxy_tags:
    - compliance
    - stig
    - windows
dependencies: []
