---
normalize_stig_findings_source_results: []
normalize_stig_findings_scan_id: ""
normalize_stig_findings_scan_type: scan
normalize_stig_findings_output_path: /tmp/compliance/cff
normalize_stig_findings_framework: DISA_STIG
